//! Markers for the machine-generated text the stripper removes.

/// Markers that condemn an entire message, not just a span of it.
///
/// These are agent-to-agent envelopes — Codex approval assessments and
/// delegation replays — that embed a whole transcript, the user own earlier
/// prompts included. Stripping them span-wise would leave that transcript
/// behind and count its swears a second time, so the message is dropped whole.
pub(super) const REJECT_WHOLE: &[&str] = &[
    "The following is the Codex agent history",
    ">>> TRANSCRIPT START",
    ">>> TRANSCRIPT DELTA START",
    "## My request for Codex:",
];

/// Tags whose entire contents are machine-generated, as their opening
/// prefix and closing tag.
///
/// Stored built rather than assembled per call: the stripper walks this
/// table for every message containing a `<`, and formatting 44 short strings
/// each time was the only allocation left on that path.
pub(super) const INJECTED_TAGS: &[(&str, &str)] = &[
    ("<system-reminder", "</system-reminder>"),
    ("<command-message", "</command-message>"),
    ("<command-name", "</command-name>"),
    ("<command-args", "</command-args>"),
    ("<command-contents", "</command-contents>"),
    ("<local-command-stdout", "</local-command-stdout>"),
    ("<local-command-stderr", "</local-command-stderr>"),
    ("<local-command-caveat", "</local-command-caveat>"),
    ("<task-notification", "</task-notification>"),
    ("<heartbeat", "</heartbeat>"),
    ("<automation_id", "</automation_id>"),
    ("<current_time_iso", "</current_time_iso>"),
    ("<bash-stdout", "</bash-stdout>"),
    ("<bash-stderr", "</bash-stderr>"),
    ("<bash-input", "</bash-input>"),
    ("<recommended_plugins", "</recommended_plugins>"),
    ("<codex_delegation", "</codex_delegation>"),
    ("<in-app-browser-context", "</in-app-browser-context>"),
    ("<user_info", "</user_info>"),
    ("<user_query", "</user_query>"),
    ("<environment_context", "</environment_context>"),
    ("<environment_details", "</environment_details>"),
];

/// Line prefixes that mark a whole injected preamble rather than a tag.
pub(super) const INJECTED_PREAMBLES: &[&str] = &[
    "# Response annotations:",
    "<recommended_plugins>",
    "Caveat: The messages below were generated by the user while running local commands.",
];
