// Removes machine-injected text from a raw user turn.
//
// Every harness routes synthetic content through the same `role: user` channel
// that carries real typed prompts: system reminders, slash-command envelopes,
// delegation payloads, ambient UI state. Matching profanity against that text
// would count words the user never typed.
//
// Code is stripped for the same reason in reverse: prompts are saturated with
// source, and identifiers like `assert`, `class`, and `bass` are where
// false-positive swear matches come from.

import { splitWhitespace, trimStartWhitespace, trimWhitespace } from "../text.js";

/**
 * Markers that condemn an entire message, not just a span of it.
 *
 * These are agent-to-agent envelopes — Codex approval assessments and
 * delegation replays — that embed a whole transcript, the user's own earlier
 * prompts included. Stripping them span-wise would leave that transcript
 * behind and count its swears a second time, so the message is dropped whole.
 */
const REJECT_WHOLE = [
  "The following is the Codex agent history",
  ">>> TRANSCRIPT START",
  ">>> TRANSCRIPT DELTA START",
  "## My request for Codex:",
];

/** Tags whose entire contents are machine-generated. */
const INJECTED_TAGS = [
  "system-reminder",
  "command-message",
  "command-name",
  "command-args",
  "command-contents",
  "local-command-stdout",
  "local-command-stderr",
  "local-command-caveat",
  "task-notification",
  "heartbeat",
  "automation_id",
  "current_time_iso",
  "bash-stdout",
  "bash-stderr",
  "bash-input",
  "recommended_plugins",
  "codex_delegation",
  "in-app-browser-context",
  "user_info",
  "user_query",
  "environment_context",
  "environment_details",
];

/** Line prefixes that mark a whole injected preamble rather than a tag. */
const INJECTED_PREAMBLES = [
  "# Response annotations:",
  "<recommended_plugins>",
  "Caveat: The messages below were generated by the user while running local commands.",
];

/**
 * Strips injected blocks and code, returning the human prose that remains, or
 * null when nothing survives — that means the turn was entirely
 * machine-generated and is not a human prompt at all.
 */
export function strip(input: string): string | null {
  if (REJECT_WHOLE.some((m) => input.includes(m))) return null;

  let text = input;
  // Each of these walks the whole string, and the tag pass walks it once per
  // tag. Most turns contain none of the characters that could trigger them —
  // 91% of the corpus holds no `<` at all — so probing for a single character
  // first skips upwards of twenty full passes over the common message.
  if (text.includes("<")) {
    for (const tag of INJECTED_TAGS) text = removeTagBlocks(text, tag);
  }
  if (text.includes("```") || text.includes("~~~")) text = removeFencedCode(text);
  if (text.includes("`")) text = removeInlineCode(text);
  // Always runs: it collapses all whitespace, which is what makes skipping the
  // fence pass (and its line-ending normalisation) unobservable downstream.
  text = removePaths(text);

  for (const preamble of INJECTED_PREAMBLES) {
    const idx = text.indexOf(preamble);
    if (idx !== -1) text = text.slice(0, idx);
  }

  const cleaned = trimWhitespace(text);
  return cleaned.length > 0 ? cleaned : null;
}

/**
 * Removes `<tag ...>...</tag>` spans, and self-closing / unclosed `<tag ...>`
 * openers. An unclosed opener swallows the rest of the input, which is the
 * correct reading: truncated injected blocks are still injected.
 */
function removeTagBlocks(input: string, tag: string): string {
  const openPrefix = `<${tag}`;
  const close = `</${tag}>`;
  let out = "";
  let rest = input;

  while (true) {
    const start = rest.indexOf(openPrefix);
    if (start === -1) return out + rest;

    // Guard against `<user_infoX>` matching the `user_info` prefix.
    const nextChar = rest[start + openPrefix.length];
    if (nextChar !== ">" && nextChar !== " " && nextChar !== "/") {
      const bump = start + openPrefix.length;
      out += rest.slice(0, bump);
      rest = rest.slice(bump);
      continue;
    }

    out += rest.slice(0, start);
    const tail = rest.slice(start);
    const end = tail.indexOf(close);
    if (end === -1) return out; // opener with no close: drop through end of input
    rest = tail.slice(end + close.length);
  }
}

/** Removes ``` and ~~~ fenced blocks, including unterminated ones. */
function removeFencedCode(input: string): string {
  let out = "";
  let inFence = false;
  let fenceChar = "`";

  for (const line of input.split("\n")) {
    const trimmed = trimStartWhitespace(line);
    if (trimmed.startsWith("```") || trimmed.startsWith("~~~")) {
      const c = trimmed[0]!;
      if (!inFence) {
        inFence = true;
        fenceChar = c;
      } else if (c === fenceChar) {
        inFence = false;
      }
      continue;
    }
    if (!inFence) out += line + "\n";
  }
  return out;
}

/** Removes backtick spans. Unmatched trailing backticks are left alone. */
function removeInlineCode(input: string): string {
  let out = "";
  let rest = input;
  while (true) {
    const start = rest.indexOf("`");
    if (start === -1) return out + rest;
    out += rest.slice(0, start);
    const tail = rest.slice(start + 1);
    const end = tail.indexOf("`");
    if (end === -1) return out + rest.slice(start);
    out += " ";
    rest = tail.slice(end + 1);
  }
}

/**
 * Blanks out bare filesystem paths, which carry directory names that read as
 * words (`~/.config/hell`, `src/assets`).
 */
function removePaths(input: string): string {
  return splitWhitespace(input).filter((tok) => !isPathLike(tok)).join(" ");
}

function isPathLike(tok: string): boolean {
  const t = tok.replace(/^[,.)(]+/, "").replace(/[,.)(]+$/, "");
  // v1 measured UTF-8 bytes here, not UTF-16 units.
  if (Buffer.byteLength(t) < 3) return false;
  if (t.startsWith("/") || t.startsWith("~/") || t.startsWith("./") || t.startsWith("../")) {
    return true;
  }
  if (!t.includes("/") || t.includes(" ")) return false;
  return (t.match(/\//g) ?? []).length >= 2;
}
