/// The canonical lexicon. Inflections are handled by suffix matching in
/// `is_word_boundary`, not by listing every form.
const LEXICON: &[(&str, Tier)] = &[
    ("damn", Tier::Mild),
    ("damnit", Tier::Mild),
    ("dammit", Tier::Mild),
    ("hell", Tier::Mild),
    ("crap", Tier::Mild),
    ("sucks", Tier::Mild),
    ("suck", Tier::Mild),
    ("screwed", Tier::Mild),
    ("goddamn", Tier::Mild),
    ("stupid", Tier::Mild),
    ("dumb", Tier::Mild),
    ("clueless", Tier::Mild),
    ("shit", Tier::Medium),
    ("bullshit", Tier::Medium),
    ("ass", Tier::Medium),
    ("arse", Tier::Medium),
    ("asshole", Tier::Medium),
    ("dumbass", Tier::Medium),
    ("bitch", Tier::Medium),
    ("dick", Tier::Medium),
    ("piss", Tier::Medium),
    ("pissed", Tier::Medium),
    ("bastard", Tier::Medium),
    ("bollocks", Tier::Medium),
    ("wanker", Tier::Medium),
    ("prick", Tier::Medium),
    ("douche", Tier::Medium),
    ("idiot", Tier::Medium),
    ("idiotic", Tier::Medium),
    ("moron", Tier::Medium),
    ("moronic", Tier::Medium),
    ("imbecile", Tier::Medium),
    ("jackass", Tier::Medium),
    ("dimwit", Tier::Medium),
    ("nitwit", Tier::Medium),
    ("halfwit", Tier::Medium),
    ("braindead", Tier::Medium),
    ("incompetent", Tier::Medium),
    ("pathetic", Tier::Medium),
    ("fuck", Tier::Strong),
    ("fucking", Tier::Strong),
    ("fucked", Tier::Strong),
    ("fucker", Tier::Strong),
    ("clusterfuck", Tier::Strong),
    ("motherfucker", Tier::Strong),
    ("cunt", Tier::Strong),
    ("retard", Tier::Strong),
    ("retarded", Tier::Strong),
    ("dumbfuck", Tier::Strong),
    ("dumbshit", Tier::Strong),
    ("dipshit", Tier::Strong),
    ("shithead", Tier::Strong),
    ("wtf", Tier::Acronym),
    ("ffs", Tier::Acronym),
    ("stfu", Tier::Acronym),
    ("omfg", Tier::Acronym),
    ("gtfo", Tier::Acronym),
    ("af", Tier::Acronym),
    ("smfh", Tier::Acronym),
];

/// Words that contain a lexicon entry as a substring but are innocent.
///
/// Matching is word-bounded, so this only needs to cover whole words that *are*
/// a swear plus affixes — the Scunthorpe class.
const ALLOWLIST: &[&str] = &[
    "assert",
    "asserts",
    "asserted",
    "assertion",
    "assertions",
    "assign",
    "assigns",
    "assigned",
    "assignment",
    "assignments",
    "asset",
    "assets",
    "associate",
    "associated",
    "association",
    "assume",
    "assumes",
    "assumed",
    "assumption",
    "assumptions",
    "assure",
    "async",
    "class",
    "classes",
    "classname",
    "pass",
    "passed",
    "passes",
    "passing",
    "password",
    "passwords",
    "bypass",
    "compass",
    "bass",
    "brass",
    "glass",
    "grass",
    "mass",
    "massive",
    "massively",
    "cassandra",
    "embassy",
    "hello",
    "shell",
    "shells",
    "shelling",
    "michelle",
    "analysis",
    "analyse",
    "analyze",
    "scunthorpe",
    "dickinson",
    "sussex",
    "essex",
    "middlesex",
    "canvas",
    "harass",
    "harassment",
    "surpass",
    "assembly",
    "assembler",
    "cassette",
    "molasses",
    "potassium",
    "assist",
    "assistant",
    "access",
    "processed",
    "oxymoron",
    "dumbbell",
    "dumbbells",
    "retardant",
    "retardants",
];

/// Grammatical endings a match may be glued to: fucking, shitty, asses, damned.
const SUFFIXES: &[&str] = &[
    "s",
    "es",
    "ed",
    "ing",
    "y",
    "er",
    "ers",
    "in",
    "in'",
    "ty",
    "tier",
    "head",
    "hole",
    "holes",
    "face",
    "wit",
    "ly",
    "ness",
];
