/// Markers that condemn an entire message, not just a span of it.
///
/// These are agent-to-agent envelopes — Codex approval assessments and
/// delegation replays — that embed a whole transcript, the user own earlier
/// prompts included. Stripping them span-wise would leave that transcript
/// behind and count its swears a second time, so the message is dropped whole.
const REJECT_WHOLE: &[&str] = &[
    "The following is the Codex agent history",
    ">>> TRANSCRIPT START",
    ">>> TRANSCRIPT DELTA START",
    "## My request for Codex:",
];

/// Tags whose entire contents are machine-generated.
const INJECTED_TAGS: &[&str] = &[
    "system-reminder",
    "command-message",
    "command-name",
    "command-args",
    "command-contents",
    "local-command-stdout",
    "local-command-stderr",
    "local-command-caveat",
    "task-notification",
    "heartbeat",
    "automation_id",
    "current_time_iso",
    "bash-stdout",
    "bash-stderr",
    "bash-input",
    "recommended_plugins",
    "codex_delegation",
    "in-app-browser-context",
    "user_info",
    "user_query",
    "environment_context",
    "environment_details",
];

/// Line prefixes that mark a whole injected preamble rather than a tag.
const INJECTED_PREAMBLES: &[&str] = &[
    "# Response annotations:",
    "<recommended_plugins>",
    "Caveat: The messages below were generated by the user while running local commands.",
];
